query PostMyFeed($params: FilterFeedPostInput!) {
  PostMyFeed(params: $params) {
    hasMore
    nextCursor
    data {
      iLiked
      likeCount
      replyCount
      post {
        _id
        ...PostFragment
      }
    }
  }
}
