query PostLikedPosts($params: FilterInput!) {
  PostLikedPosts(params: $params) {
    hasMore
    nextCursor
    data {
      iLiked
      likeCount
      replyCount
      post {
        _id
        ...PostFragment
      }
    }
  }
}
