query PostGetPostAndAllComments($postId: String!) {
  PostGetPostAndAllComments(postId: $postId) {
    replies {
      hasMore
      nextCursor
      data {
        iLiked
        likeCount
        replyCount
        post {
          _id
          ...PostFragment
        }
      }
    }
    post {
      iLiked
      likeCount
      replyCount
      post {
        _id
        ...PostFragment
      }
    }

    ancestors {
      hasMore
      nextCursor
      data {
        iLiked
        likeCount
        replyCount
        post {
          _id
          ...PostFragment
        }
      }
    }
  }
}
