query UserByUsername($username: String!) {
  UserByUsername(username: $username) {
    user {
      _id
      createdAt
      email
      followersCount
      followingCount
      followers {
        follower {
          _id
          name
          lastname
          profileImg {
            _id
            secure_url
            url
            public_id
          }
          username
        }
      }
      following {
        following {
          _id
          name
          lastname
          profileImg {
            _id
            secure_url
            url
            public_id
          }
          username
        }
      }
      lastname
      name
      profileImg {
        _id
        secure_url
        url
        public_id
      }
      bannerImg {
        _id
        secure_url
        url
        public_id
      }
      bio
      username
      birth_date
    }
    isFollowing
  }
}
