import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const geistInter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${geistInter.variable} font-inter text-white antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
