/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "fragment PostDataFragment on OnePostReturnDto {\n  iLiked\n  likeCount\n  replyCount\n  post {\n    _id\n    ...PostFragment\n  }\n}": typeof types.PostDataFragmentFragmentDoc,
    "fragment PostFragment on Post {\n  reactionsCount\n  authorId {\n    _id\n    username\n    name\n    lastname\n    profileImg {\n      _id\n      secure_url\n      public_id\n    }\n  }\n  body\n  status\n  createdAt\n  images {\n    _id\n    public_id\n    secure_url\n  }\n  tags\n  title\n  replyTo {\n    _id\n    authorId {\n      username\n      _id\n    }\n  }\n}": typeof types.PostFragmentFragmentDoc,
    "mutation AuthLogin($loginInput: LoginInput!) {\n  AuthLogin(loginInput: $loginInput) {\n    tokenWs\n  }\n}": typeof types.AuthLoginDocument,
    "mutation AuthLogout {\n  AuthLogout\n}": typeof types.AuthLogoutDocument,
    "mutation AuthRegister($file: Upload, $register: CreateUserInput!) {\n  AuthRegister(file: $file, register: $register) {\n    tokenWs\n  }\n}": typeof types.AuthRegisterDocument,
    "mutation AuthRotateAccessToken {\n  AuthRotateAccessToken {\n    tokenWs\n  }\n}": typeof types.AuthRotateAccessTokenDocument,
    "mutation PostCreatePost($data: CreatePostInput!, $files: [Upload!]!) {\n  PostCreatePost(data: $data, files: $files) {\n    _id\n    reactionsCount\n    replyTo {\n      _id\n      authorId {\n        _id\n      }\n    }\n    authorId {\n      _id\n      username\n      name\n      lastname\n      profileImg {\n        _id\n        secure_url\n        public_id\n      }\n    }\n    body\n    createdAt\n    images {\n      _id\n      public_id\n      secure_url\n    }\n    tags\n    title\n  }\n}": typeof types.PostCreatePostDocument,
    "mutation PostDeletePostUser($deletePostUserId: String!) {\n  PostDeletePostUser(id: $deletePostUserId) {\n    _id\n    status\n  }\n}": typeof types.PostDeletePostUserDocument,
    "mutation PostDislikePost($dislikePostId: String!) {\n  PostDislikePost(id: $dislikePostId) {\n    ignored\n    likedCount\n  }\n}": typeof types.PostDislikePostDocument,
    "mutation PostLikePost($likePostId: String!) {\n  PostLikePost(id: $likePostId) {\n    ignored\n    likedCount\n  }\n}": typeof types.PostLikePostDocument,
    "mutation PostReportPost($data: CreatePostReportInput!) {\n  PostReportPost(data: $data)\n}": typeof types.PostReportPostDocument,
    "mutation UserFollowUser($userToFollowId: String!) {\n  UserFollowUser(userToFollowId: $userToFollowId)\n}": typeof types.UserFollowUserDocument,
    "mutation UserUnfollow($userToUnfollowId: String!) {\n  UserUnfollow(userToUnfollowId: $userToUnfollowId)\n}": typeof types.UserUnfollowDocument,
    "mutation UserUpdate($updateUserInput: UpdateUserInput!, $bannerImg: Upload, $profileImg: Upload) {\n  UserUpdate(\n    updateUserInput: $updateUserInput\n    bannerImg: $bannerImg\n    profileImg: $profileImg\n  ) {\n    _id\n    bannerImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    bio\n    createdAt\n    email\n    followersCount\n    followingCount\n    lastname\n    name\n    profileImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    role\n    updatedAt\n    username\n  }\n}": typeof types.UserUpdateDocument,
    "query PostGetAncestorsComments($postId: String!) {\n  PostGetAncestorsComments(postId: $postId) {\n    nextCursor\n    hasMore\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        reactionsCount\n        replyTo {\n          _id\n          authorId {\n            username\n            _id\n          }\n        }\n        authorId {\n          _id\n          username\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            public_id\n          }\n        }\n        body\n        createdAt\n        images {\n          _id\n          public_id\n          secure_url\n        }\n        tags\n        title\n      }\n    }\n  }\n}": typeof types.PostGetAncestorsCommentsDocument,
    "query PostGetComments($postId: String!, $cursor: String) {\n  PostGetComments(postId: $postId, cursor: $cursor) {\n    nextCursor\n    hasMore\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        reactionsCount\n        replyTo {\n          _id\n          authorId {\n            username\n            _id\n          }\n        }\n        authorId {\n          _id\n          username\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            public_id\n          }\n        }\n        body\n        createdAt\n        images {\n          _id\n          public_id\n          secure_url\n        }\n        tags\n        title\n      }\n    }\n  }\n}": typeof types.PostGetCommentsDocument,
    "query PostGetLikesCount($postId: String!) {\n  PostGetLikesCount(postId: $postId)\n}": typeof types.PostGetLikesCountDocument,
    "query PostGetPostAndAllComments($postId: String!) {\n  PostGetPostAndAllComments(postId: $postId) {\n    replies {\n      hasMore\n      nextCursor\n      data {\n        iLiked\n        likeCount\n        replyCount\n        post {\n          _id\n          ...PostFragment\n        }\n      }\n    }\n    post {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n    ancestors {\n      hasMore\n      nextCursor\n      data {\n        iLiked\n        likeCount\n        replyCount\n        post {\n          _id\n          ...PostFragment\n        }\n      }\n    }\n  }\n}": typeof types.PostGetPostAndAllCommentsDocument,
    "query PostGetPostsByIds($postsIds: [String!]!) {\n  PostGetPostsByIds(postsIds: $postsIds) {\n    iLiked\n    likeCount\n    replyCount\n    post {\n      _id\n      ...PostFragment\n    }\n  }\n}": typeof types.PostGetPostsByIdsDocument,
    "query PostLikedPosts($params: FilterInput!) {\n  PostLikedPosts(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}": typeof types.PostLikedPostsDocument,
    "query PostMultimediaPost($params: FilterInput!) {\n  PostUserPosts(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      post {\n        _id\n        images {\n          _id\n          public_id\n          secure_url\n        }\n      }\n    }\n  }\n}": typeof types.PostMultimediaPostDocument,
    "query PostMyFeed($params: FilterFeedPostInput!) {\n  PostMyFeed(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}": typeof types.PostMyFeedDocument,
    "query PostUserPosts($params: FilterInput!) {\n  PostUserPosts(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}": typeof types.PostUserPostsDocument,
    "query UserByUsername($username: String!) {\n  UserByUsername(username: $username) {\n    user {\n      _id\n      createdAt\n      email\n      followersCount\n      followingCount\n      followers {\n        follower {\n          _id\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            url\n            public_id\n          }\n          username\n        }\n      }\n      following {\n        following {\n          _id\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            url\n            public_id\n          }\n          username\n        }\n      }\n      lastname\n      name\n      profileImg {\n        _id\n        secure_url\n        url\n        public_id\n      }\n      bannerImg {\n        _id\n        secure_url\n        url\n        public_id\n      }\n      bio\n      username\n      birth_date\n    }\n    isFollowing\n  }\n}": typeof types.UserByUsernameDocument,
    "query UserMeQuery {\n  UserMeQuery {\n    _id\n    createdAt\n    updatedAt\n    email\n    followersCount\n    followingCount\n    followers {\n      follower {\n        _id\n        name\n        lastname\n        profileImg {\n          _id\n          secure_url\n          url\n          public_id\n        }\n        username\n      }\n    }\n    following {\n      following {\n        _id\n        name\n        lastname\n        profileImg {\n          _id\n          secure_url\n          url\n          public_id\n        }\n        username\n      }\n    }\n    lastname\n    name\n    profileImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    bannerImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    bio\n    role\n    username\n    birth_date\n  }\n}": typeof types.UserMeQueryDocument,
    "query UserSuggestedUsers {\n  UserSuggestedUsers {\n    _id\n    name\n    lastname\n    username\n    profileImg {\n      _id\n      secure_url\n    }\n  }\n}": typeof types.UserSuggestedUsersDocument,
    "query ProfilePosts($multimediaPostParams: FilterInput!, $likedPostsParams: FilterInput!, $userPostsParams: FilterInput!) {\n  multimediaPosts: PostUserPosts(params: $multimediaPostParams) {\n    hasMore\n    nextCursor\n    data {\n      post {\n        _id\n        images {\n          _id\n          public_id\n          secure_url\n        }\n      }\n    }\n  }\n  PostLikedPosts(params: $likedPostsParams) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n  PostUserPosts(params: $userPostsParams) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}": typeof types.ProfilePostsDocument,
    "subscription SubNewPosts {\n  subNewPosts {\n    authorUsername\n    postId\n    authorId\n    authorProfileImg\n  }\n}": typeof types.SubNewPostsDocument,
};
const documents: Documents = {
    "fragment PostDataFragment on OnePostReturnDto {\n  iLiked\n  likeCount\n  replyCount\n  post {\n    _id\n    ...PostFragment\n  }\n}": types.PostDataFragmentFragmentDoc,
    "fragment PostFragment on Post {\n  reactionsCount\n  authorId {\n    _id\n    username\n    name\n    lastname\n    profileImg {\n      _id\n      secure_url\n      public_id\n    }\n  }\n  body\n  status\n  createdAt\n  images {\n    _id\n    public_id\n    secure_url\n  }\n  tags\n  title\n  replyTo {\n    _id\n    authorId {\n      username\n      _id\n    }\n  }\n}": types.PostFragmentFragmentDoc,
    "mutation AuthLogin($loginInput: LoginInput!) {\n  AuthLogin(loginInput: $loginInput) {\n    tokenWs\n  }\n}": types.AuthLoginDocument,
    "mutation AuthLogout {\n  AuthLogout\n}": types.AuthLogoutDocument,
    "mutation AuthRegister($file: Upload, $register: CreateUserInput!) {\n  AuthRegister(file: $file, register: $register) {\n    tokenWs\n  }\n}": types.AuthRegisterDocument,
    "mutation AuthRotateAccessToken {\n  AuthRotateAccessToken {\n    tokenWs\n  }\n}": types.AuthRotateAccessTokenDocument,
    "mutation PostCreatePost($data: CreatePostInput!, $files: [Upload!]!) {\n  PostCreatePost(data: $data, files: $files) {\n    _id\n    reactionsCount\n    replyTo {\n      _id\n      authorId {\n        _id\n      }\n    }\n    authorId {\n      _id\n      username\n      name\n      lastname\n      profileImg {\n        _id\n        secure_url\n        public_id\n      }\n    }\n    body\n    createdAt\n    images {\n      _id\n      public_id\n      secure_url\n    }\n    tags\n    title\n  }\n}": types.PostCreatePostDocument,
    "mutation PostDeletePostUser($deletePostUserId: String!) {\n  PostDeletePostUser(id: $deletePostUserId) {\n    _id\n    status\n  }\n}": types.PostDeletePostUserDocument,
    "mutation PostDislikePost($dislikePostId: String!) {\n  PostDislikePost(id: $dislikePostId) {\n    ignored\n    likedCount\n  }\n}": types.PostDislikePostDocument,
    "mutation PostLikePost($likePostId: String!) {\n  PostLikePost(id: $likePostId) {\n    ignored\n    likedCount\n  }\n}": types.PostLikePostDocument,
    "mutation PostReportPost($data: CreatePostReportInput!) {\n  PostReportPost(data: $data)\n}": types.PostReportPostDocument,
    "mutation UserFollowUser($userToFollowId: String!) {\n  UserFollowUser(userToFollowId: $userToFollowId)\n}": types.UserFollowUserDocument,
    "mutation UserUnfollow($userToUnfollowId: String!) {\n  UserUnfollow(userToUnfollowId: $userToUnfollowId)\n}": types.UserUnfollowDocument,
    "mutation UserUpdate($updateUserInput: UpdateUserInput!, $bannerImg: Upload, $profileImg: Upload) {\n  UserUpdate(\n    updateUserInput: $updateUserInput\n    bannerImg: $bannerImg\n    profileImg: $profileImg\n  ) {\n    _id\n    bannerImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    bio\n    createdAt\n    email\n    followersCount\n    followingCount\n    lastname\n    name\n    profileImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    role\n    updatedAt\n    username\n  }\n}": types.UserUpdateDocument,
    "query PostGetAncestorsComments($postId: String!) {\n  PostGetAncestorsComments(postId: $postId) {\n    nextCursor\n    hasMore\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        reactionsCount\n        replyTo {\n          _id\n          authorId {\n            username\n            _id\n          }\n        }\n        authorId {\n          _id\n          username\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            public_id\n          }\n        }\n        body\n        createdAt\n        images {\n          _id\n          public_id\n          secure_url\n        }\n        tags\n        title\n      }\n    }\n  }\n}": types.PostGetAncestorsCommentsDocument,
    "query PostGetComments($postId: String!, $cursor: String) {\n  PostGetComments(postId: $postId, cursor: $cursor) {\n    nextCursor\n    hasMore\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        reactionsCount\n        replyTo {\n          _id\n          authorId {\n            username\n            _id\n          }\n        }\n        authorId {\n          _id\n          username\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            public_id\n          }\n        }\n        body\n        createdAt\n        images {\n          _id\n          public_id\n          secure_url\n        }\n        tags\n        title\n      }\n    }\n  }\n}": types.PostGetCommentsDocument,
    "query PostGetLikesCount($postId: String!) {\n  PostGetLikesCount(postId: $postId)\n}": types.PostGetLikesCountDocument,
    "query PostGetPostAndAllComments($postId: String!) {\n  PostGetPostAndAllComments(postId: $postId) {\n    replies {\n      hasMore\n      nextCursor\n      data {\n        iLiked\n        likeCount\n        replyCount\n        post {\n          _id\n          ...PostFragment\n        }\n      }\n    }\n    post {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n    ancestors {\n      hasMore\n      nextCursor\n      data {\n        iLiked\n        likeCount\n        replyCount\n        post {\n          _id\n          ...PostFragment\n        }\n      }\n    }\n  }\n}": types.PostGetPostAndAllCommentsDocument,
    "query PostGetPostsByIds($postsIds: [String!]!) {\n  PostGetPostsByIds(postsIds: $postsIds) {\n    iLiked\n    likeCount\n    replyCount\n    post {\n      _id\n      ...PostFragment\n    }\n  }\n}": types.PostGetPostsByIdsDocument,
    "query PostLikedPosts($params: FilterInput!) {\n  PostLikedPosts(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}": types.PostLikedPostsDocument,
    "query PostMultimediaPost($params: FilterInput!) {\n  PostUserPosts(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      post {\n        _id\n        images {\n          _id\n          public_id\n          secure_url\n        }\n      }\n    }\n  }\n}": types.PostMultimediaPostDocument,
    "query PostMyFeed($params: FilterFeedPostInput!) {\n  PostMyFeed(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}": types.PostMyFeedDocument,
    "query PostUserPosts($params: FilterInput!) {\n  PostUserPosts(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}": types.PostUserPostsDocument,
    "query UserByUsername($username: String!) {\n  UserByUsername(username: $username) {\n    user {\n      _id\n      createdAt\n      email\n      followersCount\n      followingCount\n      followers {\n        follower {\n          _id\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            url\n            public_id\n          }\n          username\n        }\n      }\n      following {\n        following {\n          _id\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            url\n            public_id\n          }\n          username\n        }\n      }\n      lastname\n      name\n      profileImg {\n        _id\n        secure_url\n        url\n        public_id\n      }\n      bannerImg {\n        _id\n        secure_url\n        url\n        public_id\n      }\n      bio\n      username\n      birth_date\n    }\n    isFollowing\n  }\n}": types.UserByUsernameDocument,
    "query UserMeQuery {\n  UserMeQuery {\n    _id\n    createdAt\n    updatedAt\n    email\n    followersCount\n    followingCount\n    followers {\n      follower {\n        _id\n        name\n        lastname\n        profileImg {\n          _id\n          secure_url\n          url\n          public_id\n        }\n        username\n      }\n    }\n    following {\n      following {\n        _id\n        name\n        lastname\n        profileImg {\n          _id\n          secure_url\n          url\n          public_id\n        }\n        username\n      }\n    }\n    lastname\n    name\n    profileImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    bannerImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    bio\n    role\n    username\n    birth_date\n  }\n}": types.UserMeQueryDocument,
    "query UserSuggestedUsers {\n  UserSuggestedUsers {\n    _id\n    name\n    lastname\n    username\n    profileImg {\n      _id\n      secure_url\n    }\n  }\n}": types.UserSuggestedUsersDocument,
    "query ProfilePosts($multimediaPostParams: FilterInput!, $likedPostsParams: FilterInput!, $userPostsParams: FilterInput!) {\n  multimediaPosts: PostUserPosts(params: $multimediaPostParams) {\n    hasMore\n    nextCursor\n    data {\n      post {\n        _id\n        images {\n          _id\n          public_id\n          secure_url\n        }\n      }\n    }\n  }\n  PostLikedPosts(params: $likedPostsParams) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n  PostUserPosts(params: $userPostsParams) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}": types.ProfilePostsDocument,
    "subscription SubNewPosts {\n  subNewPosts {\n    authorUsername\n    postId\n    authorId\n    authorProfileImg\n  }\n}": types.SubNewPostsDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "fragment PostDataFragment on OnePostReturnDto {\n  iLiked\n  likeCount\n  replyCount\n  post {\n    _id\n    ...PostFragment\n  }\n}"): (typeof documents)["fragment PostDataFragment on OnePostReturnDto {\n  iLiked\n  likeCount\n  replyCount\n  post {\n    _id\n    ...PostFragment\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "fragment PostFragment on Post {\n  reactionsCount\n  authorId {\n    _id\n    username\n    name\n    lastname\n    profileImg {\n      _id\n      secure_url\n      public_id\n    }\n  }\n  body\n  status\n  createdAt\n  images {\n    _id\n    public_id\n    secure_url\n  }\n  tags\n  title\n  replyTo {\n    _id\n    authorId {\n      username\n      _id\n    }\n  }\n}"): (typeof documents)["fragment PostFragment on Post {\n  reactionsCount\n  authorId {\n    _id\n    username\n    name\n    lastname\n    profileImg {\n      _id\n      secure_url\n      public_id\n    }\n  }\n  body\n  status\n  createdAt\n  images {\n    _id\n    public_id\n    secure_url\n  }\n  tags\n  title\n  replyTo {\n    _id\n    authorId {\n      username\n      _id\n    }\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "mutation AuthLogin($loginInput: LoginInput!) {\n  AuthLogin(loginInput: $loginInput) {\n    tokenWs\n  }\n}"): (typeof documents)["mutation AuthLogin($loginInput: LoginInput!) {\n  AuthLogin(loginInput: $loginInput) {\n    tokenWs\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "mutation AuthLogout {\n  AuthLogout\n}"): (typeof documents)["mutation AuthLogout {\n  AuthLogout\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "mutation AuthRegister($file: Upload, $register: CreateUserInput!) {\n  AuthRegister(file: $file, register: $register) {\n    tokenWs\n  }\n}"): (typeof documents)["mutation AuthRegister($file: Upload, $register: CreateUserInput!) {\n  AuthRegister(file: $file, register: $register) {\n    tokenWs\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "mutation AuthRotateAccessToken {\n  AuthRotateAccessToken {\n    tokenWs\n  }\n}"): (typeof documents)["mutation AuthRotateAccessToken {\n  AuthRotateAccessToken {\n    tokenWs\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "mutation PostCreatePost($data: CreatePostInput!, $files: [Upload!]!) {\n  PostCreatePost(data: $data, files: $files) {\n    _id\n    reactionsCount\n    replyTo {\n      _id\n      authorId {\n        _id\n      }\n    }\n    authorId {\n      _id\n      username\n      name\n      lastname\n      profileImg {\n        _id\n        secure_url\n        public_id\n      }\n    }\n    body\n    createdAt\n    images {\n      _id\n      public_id\n      secure_url\n    }\n    tags\n    title\n  }\n}"): (typeof documents)["mutation PostCreatePost($data: CreatePostInput!, $files: [Upload!]!) {\n  PostCreatePost(data: $data, files: $files) {\n    _id\n    reactionsCount\n    replyTo {\n      _id\n      authorId {\n        _id\n      }\n    }\n    authorId {\n      _id\n      username\n      name\n      lastname\n      profileImg {\n        _id\n        secure_url\n        public_id\n      }\n    }\n    body\n    createdAt\n    images {\n      _id\n      public_id\n      secure_url\n    }\n    tags\n    title\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "mutation PostDeletePostUser($deletePostUserId: String!) {\n  PostDeletePostUser(id: $deletePostUserId) {\n    _id\n    status\n  }\n}"): (typeof documents)["mutation PostDeletePostUser($deletePostUserId: String!) {\n  PostDeletePostUser(id: $deletePostUserId) {\n    _id\n    status\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "mutation PostDislikePost($dislikePostId: String!) {\n  PostDislikePost(id: $dislikePostId) {\n    ignored\n    likedCount\n  }\n}"): (typeof documents)["mutation PostDislikePost($dislikePostId: String!) {\n  PostDislikePost(id: $dislikePostId) {\n    ignored\n    likedCount\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "mutation PostLikePost($likePostId: String!) {\n  PostLikePost(id: $likePostId) {\n    ignored\n    likedCount\n  }\n}"): (typeof documents)["mutation PostLikePost($likePostId: String!) {\n  PostLikePost(id: $likePostId) {\n    ignored\n    likedCount\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "mutation PostReportPost($data: CreatePostReportInput!) {\n  PostReportPost(data: $data)\n}"): (typeof documents)["mutation PostReportPost($data: CreatePostReportInput!) {\n  PostReportPost(data: $data)\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "mutation UserFollowUser($userToFollowId: String!) {\n  UserFollowUser(userToFollowId: $userToFollowId)\n}"): (typeof documents)["mutation UserFollowUser($userToFollowId: String!) {\n  UserFollowUser(userToFollowId: $userToFollowId)\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "mutation UserUnfollow($userToUnfollowId: String!) {\n  UserUnfollow(userToUnfollowId: $userToUnfollowId)\n}"): (typeof documents)["mutation UserUnfollow($userToUnfollowId: String!) {\n  UserUnfollow(userToUnfollowId: $userToUnfollowId)\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "mutation UserUpdate($updateUserInput: UpdateUserInput!, $bannerImg: Upload, $profileImg: Upload) {\n  UserUpdate(\n    updateUserInput: $updateUserInput\n    bannerImg: $bannerImg\n    profileImg: $profileImg\n  ) {\n    _id\n    bannerImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    bio\n    createdAt\n    email\n    followersCount\n    followingCount\n    lastname\n    name\n    profileImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    role\n    updatedAt\n    username\n  }\n}"): (typeof documents)["mutation UserUpdate($updateUserInput: UpdateUserInput!, $bannerImg: Upload, $profileImg: Upload) {\n  UserUpdate(\n    updateUserInput: $updateUserInput\n    bannerImg: $bannerImg\n    profileImg: $profileImg\n  ) {\n    _id\n    bannerImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    bio\n    createdAt\n    email\n    followersCount\n    followingCount\n    lastname\n    name\n    profileImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    role\n    updatedAt\n    username\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query PostGetAncestorsComments($postId: String!) {\n  PostGetAncestorsComments(postId: $postId) {\n    nextCursor\n    hasMore\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        reactionsCount\n        replyTo {\n          _id\n          authorId {\n            username\n            _id\n          }\n        }\n        authorId {\n          _id\n          username\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            public_id\n          }\n        }\n        body\n        createdAt\n        images {\n          _id\n          public_id\n          secure_url\n        }\n        tags\n        title\n      }\n    }\n  }\n}"): (typeof documents)["query PostGetAncestorsComments($postId: String!) {\n  PostGetAncestorsComments(postId: $postId) {\n    nextCursor\n    hasMore\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        reactionsCount\n        replyTo {\n          _id\n          authorId {\n            username\n            _id\n          }\n        }\n        authorId {\n          _id\n          username\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            public_id\n          }\n        }\n        body\n        createdAt\n        images {\n          _id\n          public_id\n          secure_url\n        }\n        tags\n        title\n      }\n    }\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query PostGetComments($postId: String!, $cursor: String) {\n  PostGetComments(postId: $postId, cursor: $cursor) {\n    nextCursor\n    hasMore\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        reactionsCount\n        replyTo {\n          _id\n          authorId {\n            username\n            _id\n          }\n        }\n        authorId {\n          _id\n          username\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            public_id\n          }\n        }\n        body\n        createdAt\n        images {\n          _id\n          public_id\n          secure_url\n        }\n        tags\n        title\n      }\n    }\n  }\n}"): (typeof documents)["query PostGetComments($postId: String!, $cursor: String) {\n  PostGetComments(postId: $postId, cursor: $cursor) {\n    nextCursor\n    hasMore\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        reactionsCount\n        replyTo {\n          _id\n          authorId {\n            username\n            _id\n          }\n        }\n        authorId {\n          _id\n          username\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            public_id\n          }\n        }\n        body\n        createdAt\n        images {\n          _id\n          public_id\n          secure_url\n        }\n        tags\n        title\n      }\n    }\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query PostGetLikesCount($postId: String!) {\n  PostGetLikesCount(postId: $postId)\n}"): (typeof documents)["query PostGetLikesCount($postId: String!) {\n  PostGetLikesCount(postId: $postId)\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query PostGetPostAndAllComments($postId: String!) {\n  PostGetPostAndAllComments(postId: $postId) {\n    replies {\n      hasMore\n      nextCursor\n      data {\n        iLiked\n        likeCount\n        replyCount\n        post {\n          _id\n          ...PostFragment\n        }\n      }\n    }\n    post {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n    ancestors {\n      hasMore\n      nextCursor\n      data {\n        iLiked\n        likeCount\n        replyCount\n        post {\n          _id\n          ...PostFragment\n        }\n      }\n    }\n  }\n}"): (typeof documents)["query PostGetPostAndAllComments($postId: String!) {\n  PostGetPostAndAllComments(postId: $postId) {\n    replies {\n      hasMore\n      nextCursor\n      data {\n        iLiked\n        likeCount\n        replyCount\n        post {\n          _id\n          ...PostFragment\n        }\n      }\n    }\n    post {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n    ancestors {\n      hasMore\n      nextCursor\n      data {\n        iLiked\n        likeCount\n        replyCount\n        post {\n          _id\n          ...PostFragment\n        }\n      }\n    }\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query PostGetPostsByIds($postsIds: [String!]!) {\n  PostGetPostsByIds(postsIds: $postsIds) {\n    iLiked\n    likeCount\n    replyCount\n    post {\n      _id\n      ...PostFragment\n    }\n  }\n}"): (typeof documents)["query PostGetPostsByIds($postsIds: [String!]!) {\n  PostGetPostsByIds(postsIds: $postsIds) {\n    iLiked\n    likeCount\n    replyCount\n    post {\n      _id\n      ...PostFragment\n    }\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query PostLikedPosts($params: FilterInput!) {\n  PostLikedPosts(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}"): (typeof documents)["query PostLikedPosts($params: FilterInput!) {\n  PostLikedPosts(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query PostMultimediaPost($params: FilterInput!) {\n  PostUserPosts(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      post {\n        _id\n        images {\n          _id\n          public_id\n          secure_url\n        }\n      }\n    }\n  }\n}"): (typeof documents)["query PostMultimediaPost($params: FilterInput!) {\n  PostUserPosts(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      post {\n        _id\n        images {\n          _id\n          public_id\n          secure_url\n        }\n      }\n    }\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query PostMyFeed($params: FilterFeedPostInput!) {\n  PostMyFeed(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}"): (typeof documents)["query PostMyFeed($params: FilterFeedPostInput!) {\n  PostMyFeed(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query PostUserPosts($params: FilterInput!) {\n  PostUserPosts(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}"): (typeof documents)["query PostUserPosts($params: FilterInput!) {\n  PostUserPosts(params: $params) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query UserByUsername($username: String!) {\n  UserByUsername(username: $username) {\n    user {\n      _id\n      createdAt\n      email\n      followersCount\n      followingCount\n      followers {\n        follower {\n          _id\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            url\n            public_id\n          }\n          username\n        }\n      }\n      following {\n        following {\n          _id\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            url\n            public_id\n          }\n          username\n        }\n      }\n      lastname\n      name\n      profileImg {\n        _id\n        secure_url\n        url\n        public_id\n      }\n      bannerImg {\n        _id\n        secure_url\n        url\n        public_id\n      }\n      bio\n      username\n      birth_date\n    }\n    isFollowing\n  }\n}"): (typeof documents)["query UserByUsername($username: String!) {\n  UserByUsername(username: $username) {\n    user {\n      _id\n      createdAt\n      email\n      followersCount\n      followingCount\n      followers {\n        follower {\n          _id\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            url\n            public_id\n          }\n          username\n        }\n      }\n      following {\n        following {\n          _id\n          name\n          lastname\n          profileImg {\n            _id\n            secure_url\n            url\n            public_id\n          }\n          username\n        }\n      }\n      lastname\n      name\n      profileImg {\n        _id\n        secure_url\n        url\n        public_id\n      }\n      bannerImg {\n        _id\n        secure_url\n        url\n        public_id\n      }\n      bio\n      username\n      birth_date\n    }\n    isFollowing\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query UserMeQuery {\n  UserMeQuery {\n    _id\n    createdAt\n    updatedAt\n    email\n    followersCount\n    followingCount\n    followers {\n      follower {\n        _id\n        name\n        lastname\n        profileImg {\n          _id\n          secure_url\n          url\n          public_id\n        }\n        username\n      }\n    }\n    following {\n      following {\n        _id\n        name\n        lastname\n        profileImg {\n          _id\n          secure_url\n          url\n          public_id\n        }\n        username\n      }\n    }\n    lastname\n    name\n    profileImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    bannerImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    bio\n    role\n    username\n    birth_date\n  }\n}"): (typeof documents)["query UserMeQuery {\n  UserMeQuery {\n    _id\n    createdAt\n    updatedAt\n    email\n    followersCount\n    followingCount\n    followers {\n      follower {\n        _id\n        name\n        lastname\n        profileImg {\n          _id\n          secure_url\n          url\n          public_id\n        }\n        username\n      }\n    }\n    following {\n      following {\n        _id\n        name\n        lastname\n        profileImg {\n          _id\n          secure_url\n          url\n          public_id\n        }\n        username\n      }\n    }\n    lastname\n    name\n    profileImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    bannerImg {\n      _id\n      secure_url\n      url\n      public_id\n    }\n    bio\n    role\n    username\n    birth_date\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query UserSuggestedUsers {\n  UserSuggestedUsers {\n    _id\n    name\n    lastname\n    username\n    profileImg {\n      _id\n      secure_url\n    }\n  }\n}"): (typeof documents)["query UserSuggestedUsers {\n  UserSuggestedUsers {\n    _id\n    name\n    lastname\n    username\n    profileImg {\n      _id\n      secure_url\n    }\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query ProfilePosts($multimediaPostParams: FilterInput!, $likedPostsParams: FilterInput!, $userPostsParams: FilterInput!) {\n  multimediaPosts: PostUserPosts(params: $multimediaPostParams) {\n    hasMore\n    nextCursor\n    data {\n      post {\n        _id\n        images {\n          _id\n          public_id\n          secure_url\n        }\n      }\n    }\n  }\n  PostLikedPosts(params: $likedPostsParams) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n  PostUserPosts(params: $userPostsParams) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}"): (typeof documents)["query ProfilePosts($multimediaPostParams: FilterInput!, $likedPostsParams: FilterInput!, $userPostsParams: FilterInput!) {\n  multimediaPosts: PostUserPosts(params: $multimediaPostParams) {\n    hasMore\n    nextCursor\n    data {\n      post {\n        _id\n        images {\n          _id\n          public_id\n          secure_url\n        }\n      }\n    }\n  }\n  PostLikedPosts(params: $likedPostsParams) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n  PostUserPosts(params: $userPostsParams) {\n    hasMore\n    nextCursor\n    data {\n      iLiked\n      likeCount\n      replyCount\n      post {\n        _id\n        ...PostFragment\n      }\n    }\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "subscription SubNewPosts {\n  subNewPosts {\n    authorUsername\n    postId\n    authorId\n    authorProfileImg\n  }\n}"): (typeof documents)["subscription SubNewPosts {\n  subNewPosts {\n    authorUsername\n    postId\n    authorId\n    authorProfileImg\n  }\n}"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;